# https://docs.netlify.com/configure-builds/file-based-configuration/
# This file will completely override the UI settings

# NOTE: Deploy Previews are NOT automatically deleted when PRs are closed/merged
# https://community.netlify.com/t/does-each-deploy-preview-stay-available-forever/12601/9

# Goals:
# * Disable production release (don't need it)
#   * Set the production branch (in UI) to "does-not-exist"
# * Enable Pull Request / Merge deploy-preview context for branches
# * Disable branch-deploy context (we use previews only)
#   * Disable by default (using ignore)
#   * Add "master" to the branch deploy list

# Using ignore:
# https://docs.netlify.com/configure-builds/file-based-configuration/#ignore-builds
# An exit-code of 1 indicates the contents have changed, so if your command returns
# that code the build process will continue per usual. An exit-code of 0 indicates
# that the build should return early.

[build]
  # Directory to change to before starting a build.
  # This is where we will look for package.json/.nvmrc/etc.
  base = "/"

  # Directory that contains the deploy-ready HTML files and assets generated by
  # the build. This is relative to the base directory if one has been set, or the
  # root directory if a base has not been set. This sample publishes the
  # directory located at the absolute path "root/project/build-output"
  publish = "_site/"

  # Default build command.
  command = "jekyll build"

# Production context: all deploys from the Production branch set in your site's
# deploy contexts will inherit these settings.
[context.production]
  ignore = "exit 0"

# Deploy Preview context: all deploys generated from a pull/merge request will
# inherit these settings.
[context.deploy-preview]
  #publish = "_site/"

# Branch Deploy context: all deploys that are not from a pull/merge request or
# from the Production branch will inherit these settings.
[context.branch-deploy]
  ignore = "exit 0"
